name: Deploy Todo App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t your-docker-username/todo-node-app:latest ./Todo-List-nodejs
        working-directory: ./Todo-List-nodejs

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push olarashad/todo-node-app:latest
        working-directory: ./Todo-List-nodejs

      # Optional: SCP or SSH deployment steps here...
